[variables]
PYTHON_VERSION = "3.11"

[phases.setup]
nixPkgs = ["python311", "python311Packages.pip", "python311Packages.setuptools", "python311Packages.wheel"]

[phases.install]
cmd = """
python --version
python -m pip --version
python -m pip install --upgrade pip
python -m pip install -r requirements.txt
"""

[start]
cmd = "python app.py"